const auction = {
    id: 64,
    status: 'current',
    title: 'Spring 2020 Auction',
    date: {
        date: '2020-06-01',
        display: 'May 3-10, 2020',
        displayAbbrev: 'May 3-10, 2020',
    },
    description: '<p>LAMA\'s timed May 3-10, 2020 Online Only Auction featured 30 hand-selected works from Peter Alexander, Lita Albuquerque, John Baldessari, Sam Durant, Frank Romero, Ed Ruscha, Andy Warhol, and more. Top-selling lots included two Peter Alexander paintings (Combo 32 and Lancaster), Lita Albuquerque\'s 1975 Ereimul Series #4, Carlos Almaraz\'s City Bridge, and Frank Romero\'s The Closing of Whittier Boulevard.&nbsp;</p>\n<p><a href="/auctions/2020/06/1/results">See prices realized here</a></p>',
    lots: [
        {
            id: 35001,
            number: 1,
            title: 'Shoes',
            estimate_low: '$4,000',
            estimate_high: '$6,000',
            date: '1980; published 1981',
            medium: '1-color lithograph on Rives BFK paper',
            artist: 'Philip Guston',
            images: {
                small: 'Lot-small-001.jpg',
                large: 'Lot-large-001.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35002,
            number: 2,
            title: 'As Soon As I Get Around To It',
            estimate_low: '$3,000',
            estimate_high: '$5,000',
            date: '1993',
            medium: 'Crayon on paper',
            artist: 'Sam Durant',
            images: {
                small: 'Lot-small-002.jpg',
                large: 'Lot-large-002.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35003,
            number: 3,
            title: 'The Overlap Series: Double Motorcyclists and Landscape (Icelandic 2003)',
            estimate_low: '$4,000',
            estimate_high: '$6,000',
            date: '2001-2003',
            medium: '6-color lithograph on Somerset Satin paper',
            artist: 'John Baldessari',
            images: {
                small: 'Lot-small-003.jpg',
                large: 'Lot-large-003.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35004,
            number: 4,
            title: 'Reloj',
            estimate_low: '$2,500',
            estimate_high: '$3,500',
            date: '1988',
            medium: '3-color etching on handmade paper',
            artist: 'Ed Ruscha',
            images: {
                small: 'Lot-small-004.jpg',
                large: 'Lot-large-004.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35005,
            number: 5,
            title: 'You Will Eat Hot Lead (from Country Cityscapes)',
            estimate_low: '$2,500',
            estimate_high: '$3,500',
            date: '2001',
            medium: 'Photogravure with screenprint on paper',
            artist: 'Ed Ruscha',
            images: {
                small: 'Lot-small-005.jpg',
                large: 'Lot-large-005.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35006,
            number: 6,
            title: 'This Desire, Beloved and Despised, Continues Regardless',
            estimate_low: '$2,000',
            estimate_high: '$3,000',
            date: '1989',
            medium: '9-color lithograph and screenprint on Arches 88 paper',
            artist: 'Lari Pittman',
            images: {
                small: 'Lot-small-006.jpg',
                large: 'Lot-large-006.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35007,
            number: 7,
            title: '31 Flavors Invading Japan / Today\'s Special',
            estimate_low: '$1,000',
            estimate_high: '$1,500',
            date: '1981',
            medium: '35-color woodcut with hand-coloring on Hosho paper',
            artist: 'Masami Teraoka',
            images: {
                small: 'Lot-small-007.jpg',
                large: 'Lot-large-007.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35008,
            number: 8,
            title: 'The Umbrellas, Joint Project for Japan and U.S.A',
            estimate_low: '$800',
            estimate_high: '$1,200',
            date: '1991',
            medium: 'Color offset lithograph and fabric collage on two sheets of paper mounted to museum board',
            artist: 'Christo',
            images: {
                small: 'Lot-small-008.jpg',
                large: 'Lot-large-008.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35009,
            number: 9,
            title: 'Donna Shire Mask',
            estimate_low: '$1,500',
            estimate_high: '$2,000',
            date: '1985',
            medium: 'Mixed-media',
            artist: 'Peter Shire',
            images: {
                small: 'Lot-small-009.jpg',
                large: 'Lot-large-009.jpg',
            },
            category: 'Ceramics',
        },
        {
            id: 35010,
            number: 10,
            title: 'Face Flag (3)',
            estimate_low: '$1,000',
            estimate_high: '$1,500',
            date: '1984',
            medium: 'Color lithograph on three sheets of Rives BFK paper with grommets',
            artist: 'Vito Acconci',
            images: {
                small: 'Lot-small-010.jpg',
                large: 'Lot-large-010.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35011,
            number: 11,
            title: 'Chest',
            estimate_low: '$2,000',
            estimate_high: '$3,000',
            date: '1968',
            medium: 'Vacuum-formed acrylic and cellulose',
            artist: 'Allen Jones',
            images: {
                small: 'Lot-small-011.jpg',
                large: 'Lot-large-011.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35012,
            number: 12,
            title: 'Campbell\'s Soup Can (Tomato)',
            estimate_low: '$1,200',
            estimate_high: '$1,800',
            date: '1966',
            medium: 'Screenprint on shopping bag',
            artist: 'Andy Warhol',
            images: {
                small: 'Lot-small-012.jpg',
                large: 'Lot-large-012.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35013,
            number: 13,
            title: 'Marilyn (Castelli Graphics Invitation)',
            estimate_low: '$3,000',
            estimate_high: '$5,000',
            date: '1981',
            medium: 'Offset color lithograph on wove paper',
            artist: 'Andy Warhol',
            images: {
                small: 'Lot-small-013.jpg',
                large: 'Lot-large-013.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35015,
            number: 15,
            title: 'Untitled (Fingerprints)',
            estimate_low: '$2,000',
            estimate_high: '$3,000',
            date: '1965',
            medium: 'Gouache on Strathmore paper',
            artist: 'Emerson Woelffer',
            images: {
                small: 'Lot-small-015.jpg',
                large: 'Lot-large-015.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35016,
            number: 16,
            title: 'Abstraction No. 25',
            estimate_low: '$4,000',
            estimate_high: '$6,000',
            date: '1962',
            medium: 'Oil on canvas',
            artist: 'Oskar Fischinger',
            images: {
                small: 'Lot-small-016.jpg',
                large: 'Lot-large-016.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35017,
            number: 17,
            title: 'Rosafied',
            estimate_low: '$800',
            estimate_high: '$1,200',
            date: '1971',
            medium: 'Screenprint on wove paper',
            artist: 'Richard Anuszkiewicz',
            images: {
                small: 'Lot-small-017.jpg',
                large: 'Lot-large-017.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35018,
            number: 18,
            title: 'Untitled (#984)',
            estimate_low: '$2,000',
            estimate_high: '$3,000',
            date: '1984',
            medium: 'Oil on canvas',
            artist: 'Don Sorenson',
            images: {
                small: 'Lot-small-018.jpg',
                large: 'Lot-large-018.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35019,
            number: 19,
            title: 'Untitled',
            estimate_low: '$3,000',
            estimate_high: '$5,000',
            date: '1974',
            medium: 'Watercolor and pencil on paper',
            artist: 'Craig Kauffman',
            images: {
                small: 'Lot-small-019.jpg',
                large: 'Lot-large-019.jpg',
            },
            category: 'Fine Art',
        },
        {
            id: 35020,
            number: 20,
            title: 'Untitled',
            estimate_low: '$3,000',
            estimate_high: '$5,000',
            date: '1981',
            medium: 'Cast bronze',
            artist: 'Charles Arnoldi',
            images: {
                small: 'Lot-small-020.jpg',
                large: 'Lot-large-020.jpg',
            },
            category: 'Sculpture',
        },
    ]
}

export default auction;